environment:
  matrix:
    - TOXENV: "py27"
    - TOXENV: "py36"
    - TOXENV: "pypy"

install:
  - if "%TOXENV%" == "pypy" choco install python.pypy;
  - pip install tox

build: false  # Not a C# project, build stuff at the test step instead

test_script:
  - tox -e %TOXENV%
