sudo: false

language: python

python:
  - 2.7
  - 3.6

install:
  - pip install -r requirements.txt

script:
  - coverage run tests.py false

after_success:
  - coverage report
  - bash <(curl -s https://codecov.io/bash)
