sudo: false

language: python

python:
  - 2.7
  - 3.6

install:
  - pip install .[test]

script:
  - coverage run setup.py test

after_success:
  - coverage combine
  - coverage report
  - bash <(curl -s https://codecov.io/bash)
